# Generated by Django 4.2.4 on 2023-09-06 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_planet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 23, 8, 46, 794114, tzinfo=datetime.timezone.utc)),
        ),
    ]
